SHELL:=/bin/bash

lint:
	cd hello-world && make lint
	cd two-fer && make lint
	cd reverse-string && make lint

test:
	cd hello-world && make test
	cd two-fer && make test
	cd reverse-string && make test