SHELL:=/bin/bash

lint:
	cd hello-world && make lint
	cd two-fer && make lint
	cd reverse-string && make lint
	cd rna-transcription && make lint
	cd high-scores && make lint

test:
	cd hello-world && make test
	cd two-fer && make test
	cd reverse-string && make test
	cd rna-transcription && make test
	cd high-scores && make test